# Generated by Django 4.2.27 on 2025-12-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Samsung', 'Samsung'), ('Other', 'Other')], max_length=50)),
                ('processor', models.CharField(choices=[('i3', 'Intel i3'), ('i5', 'Intel i5'), ('i7', 'Intel i7'), ('i9', 'Intel i9'), ('Ryzen3', 'AMD Ryzen 3'), ('Ryzen5', 'AMD Ryzen 5'), ('Ryzen7', 'AMD Ryzen 7'), ('M1', 'Apple M1'), ('M2', 'Apple M2')], max_length=50)),
                ('gpu', models.CharField(choices=[('Integrated', 'Integrated'), ('GTX1650', 'GTX 1650'), ('GTX1660', 'GTX 1660'), ('RTX3050', 'RTX 3050'), ('RTX3060', 'RTX 3060'), ('RTX4060', 'RTX 4060')], max_length=50)),
                ('age_years', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('material', models.CharField(choices=[('Plastic', 'Plastic'), ('Aluminum', 'Aluminum'), ('Mixed', 'Mixed')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='RecyclingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_brand', models.CharField(max_length=50)),
                ('device_processor', models.CharField(max_length=50)),
                ('estimated_value', models.FloatField()),
                ('carbon_saved', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
