# Generated by Django 4.2.27 on 2026-03-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recyclinglog_user_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('ram_gb', models.IntegerField(default=8)),
                ('storage_gb', models.IntegerField(default=256)),
                ('pristine_price', models.FloatField(help_text='Like new, no scratches')),
                ('mint_price', models.FloatField(help_text='Minor wear, fully functional')),
                ('overused_price', models.FloatField(help_text='Heavy wear, functional')),
                ('release_year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Device Prices',
                'ordering': ['-release_year', 'brand'],
            },
        ),
        migrations.AddField(
            model_name='recyclinglog',
            name='device_condition',
            field=models.CharField(default='mint', max_length=20),
        ),
    ]
